In [1]:
import numpy as np
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
print(z.shape)
print(z.ndim)
print(z.dtype)

(3, 3)
2
int64


In [5]:
k=np.arange(1,10).reshape(3,3)
print(k)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2nd question


In [6]:
A = np.array([[10,20,30],
[40,50,60],
[70,80,90]])


In [9]:
flag=1
for i in range(3):
    for j in range(3):
								if(A[i][j]==50):
									print("Element found at index: ",i+1,j+1)
									flag=0
if(flag==1):
				print("Element not found")
else:
				print("Element found")
							
								
                                                                

Element found at index:  2 2
Element found


3rd question


In [ ]:
A = [[1,2],
[3,4]]
B = [[5,6],
[7,8]]
c=np.add(A,B)
d=np.subtract(A,B)
e=np.multiply(A,B)
f=np.divide(A,B)
print(c)
print(d)
print(e)
print(f)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
c=[]
for i in range(2):
    c.append([])
    for j in range(2):
						c[i].append(A[i][j]+B[i][j])
print(c)                                           

[[6, 8], [10, 12]]


In [17]:
add=[[A[i][j]+B[i][j] for j in range(2)] for i in range(2)]
print(add)

[[6, 8], [10, 12]]


4th problem


In [21]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Using * :", A * B)        # Element-wise multiplication
print("Using dot():", A.dot(B)) # Matrix multiplication
print("Using @ :", A @ B)       # Matrix multiplication


Using * : [[ 5 12]
 [21 32]]
Using dot(): [[19 22]
 [43 50]]
Using @ : [[19 22]
 [43 50]]


6th problem

In [23]:
import random
z=np.random.randint(1,20,16).reshape(4,4)
print(z)

[[ 1 14 14 18]
 [ 9  8 12 19]
 [ 6  9  3  9]
 [18  1 10  3]]


In [26]:
sum=np.sum(z[0])
max=np.max(z[0])
min=np.min(z[0])
print(sum)
print(max)
print(min)

47
18
1


In [30]:
col=np.sum(z[0:4,0])
print(col)

34


In [31]:
import numpy as np

# 1. Create a 3x2 matrix
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

print("Original matrix:\n", matrix)
print("Shape before:", matrix.shape)

# 2. Transpose to 2x3
transpose = matrix.T

print("Transposed matrix:\n", transpose)
print("Shape after:", transpose.shape)


Original matrix:
 [[1 2]
 [3 4]
 [5 6]]
Shape before: (3, 2)
Transposed matrix:
 [[1 3 5]
 [2 4 6]]
Shape after: (2, 3)


In [32]:
import numpy as np

# 1. 5x5 Identity Matrix
identity = np.eye(5, dtype=int)
print("5x5 Identity Matrix:\n", identity)

# 2. 3x4 Zero Matrix
zero_matrix = np.zeros((3, 4), dtype=int)
print("\n3x4 Zero Matrix:\n", zero_matrix)

# 3. 2x2 Matrix filled with 7
seven_matrix = np.full((2, 2), 7)
print("\n2x2 Matrix filled with 7:\n", seven_matrix)

5x5 Identity Matrix:
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

3x4 Zero Matrix:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

2x2 Matrix filled with 7:
 [[7 7]
 [7 7]]


In [33]:
import numpy as np

A = np.array([[12, 5, 8],
              [20, 15, 3],
              [7, 18, 10]])

# 1 & 2. Replace using condition
A[A < 10] = 0
A[A >= 10] = 1

print("Result (with NumPy):\n", A)


Result (with NumPy):
 [[1 0 0]
 [1 1 0]
 [0 1 1]]


In [34]:
print(np.diag(matrix))
print(np.trace(matrix))

[1 4]
5


In [36]:
marks = [
    [78, 85, 90],
    [88, 76, 92],
    [69, 80, 75],
    [90, 95, 85]
]

# 1. Total marks of each student
total_marks = [sum(student) for student in marks]
print("Total marks of each student:", total_marks)

# 2. Average marks per subject
num_students = len(marks)
num_subjects = len(marks[0])

avg_per_subject = [
    sum(marks[i][j] for i in range(num_students)) / num_students
    for j in range(num_subjects)
]
print("Average marks per subject:", avg_per_subject)

# 3. Find the topper (highest total)
topper_index = total_marks.index(max(total_marks))
print("Topper (student index):", topper_index)
print("Topper total marks:", total_marks[topper_index])


TypeError: 'numpy.int64' object is not callable

In [1]:
# now i want to download as pdf	and excel file
!jupyter nbconvert --to html numpy.ipynb
!jupyter nbconvert --to pdf numpy.ipynb

[NbConvertApp] Converting notebook numpy.ipynb to html
[NbConvertApp] Writing 313405 bytes to numpy.html
[NbConvertApp] Converting notebook numpy.ipynb to pdf
[NbConvertApp] ERROR | Error while converting 'numpy.ipynb'
Traceback (most recent call last):
  File "C:\Users\saian\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbconvert\nbconvertapp.py", line 487, in export_single_notebook
    output, resources = self.exporter.from_filename(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saian\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbconvert\exporters\templateexporter.py", line 390, in from_filename
    return super().from_filename(filename, resources, **kw)  # type:ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saian\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbconvert\exporters\exporter.py", line 201, in from_filename
    return self.from_file(f, resources=resources, **kw